[phases.setup]
nixPkgs = ["python313", "uv", "nodejs"]

[phases.install]
cmds = ["cd server && uv sync --frozen", "cd web && npm ci && npm run build"]

[start]
cmd = "cd server && uv run smeecher-graph"

[variables]
DATA_DIR = "/data"
