[phases.setup]
nixPkgs = ["python313", "uv", "nodejs"]

[phases.install]
cmds = [
    "uv sync --frozen --directory server",
    "cd web && npm ci && npm run build"
]

[start]
cmd = "uv run --directory server smeecher-graph"
